# Generated by Django 3.0.6 on 2020-05-09 10:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('github_link', models.CharField(max_length=64)),
                ('product_file', models.FileField(upload_to=main.models.product_directory_path)),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to='products/icons/')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='products/images/')),
            ],
        ),
    ]
