# Generated by Django 3.0.6 on 2020-05-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200509_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='github_link',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
