# Generated by Django 3.0.6 on 2020-05-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('main_text', models.TextField()),
                ('more_link', models.CharField(max_length=64)),
                ('published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
