# Generated by Django 3.0.6 on 2020-05-14 08:31

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=main.models.article_directory_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(auto_now=True),
        ),
    ]
