# Generated by Django 3.0.6 on 2020-05-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200514_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published',
            new_name='pub_date',
        ),
    ]
