# Generated by Django 3.0.6 on 2020-05-14 08:36

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200514_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=main.models.article_directory_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='more_link',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='github_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=main.models.product_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=main.models.product_directory_path),
        ),
    ]
